[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://www.thewollastongardens.com https://thewollastongardens.com;"

[[redirects]]
  from = "https://sponsors.thewollastongardens.com/*"
  to = "https://sponsors.thewollastongardens.com/sponsors"
  status = 200
  force = true
